train:
  name: Periodic/Inf
  type: GP
  batch_size: null
  shuffle: False
  drop_last: False
  gp:
    kernel: !include configs/gp/periodic/kernel.yaml
    data_size: null
    batch_size: 256
    max_num_points: 50
    x_range: [-2, 2]
    t_noise: null
valid:  !include configs/gp/periodic/datasets_test.yaml
test:   !include configs/gp/periodic/datasets_test.yaml
shapes: !include configs/gp/gp_shapes.yaml
