datasets:  !include configs/gp/matern/inf/datasets.yaml
model:     !include configs/gp/models/convbnp.yaml
optimizer: !include configs/gp/optimizer.yaml
train:     !include configs/gp/matern/inf/train.yaml
test:      !include configs/gp/matern/test.yaml
