datasets:  !include configs/image/mnist/datasets.yaml
model:     !include configs/image/models/convbnp.yaml
optimizer: !include configs/image/optimizer.yaml
train:     !include configs/image/mnist/train.yaml
test:      !include configs/image/mnist/test.yaml
