datasets:  !include configs/gp/t_noise/250/datasets.yaml
model:     !include configs/gp/models/cnp.yaml
optimizer: !include configs/gp/optimizer.yaml
train:     !include configs/gp/t_noise/250/train.yaml
test:      !include configs/gp/t_noise/test.yaml
