name: BNP
kwargs:
  r_dim: 128
  encoder_dims: [128, 128, 128, 128, 128]
  decoder_dims: [128, 128, 128]
  min_sigma: 0.1
train_kwargs:
  num_samples: 10
  joint: True
  return_aux: True
valid_kwargs:
  num_samples: 10
  joint: False
test_kwargs:
  num_samples: 10
  joint: False
