name: NeuBNP
kwargs:
  r_dim: 128
  encoder_dims: [128, 128, 128, 128, 128]
  decoder_dims: [128, 128, 128]
train_kwargs:
  num_samples: 10
  joint: False
  return_aux: True
valid_kwargs:
  num_samples: 10
test_kwargs:
  num_samples: 10
