name: ConvNP
kwargs:
  z_dim: 64
  r_dim: 64
  cnn_dims: null  # use default
  cnn_xl: False
  on_the_grid: True
  points_per_unit: 64
  loss_type: ml
  min_sigma: 0.1
  min_latent_sigma: 0.1
train_kwargs:
  num_latents: 5
  joint: True
  return_aux: True
valid_kwargs:
  num_latents: 5
  joint: False
test_kwargs:
  num_latents: 5
  joint: False
