name: ConvNP
kwargs:
  x_min: -2.0
  x_max: +2.0
  z_dim: 64
  cnn_dims: null  # use default
  cnn_xl: False
  points_per_unit: 64
  x_margin: 0.1
train_kwargs:
  num_latents: 10
valid_kwargs:
  num_latents: 10
test_kwargs:
  num_latents: 10
