name: NeuBNP
kwargs:
  r_dim: 128
  encoder_dims: [128, 128, 128, 128, 128]
  decoder_dims: [128, 128, 128]
  min_sigma: 0.1
train_kwargs:
  num_samples: 5
  joint: True
valid_kwargs:
  num_samples: 5
  joint: False
test_kwargs:
  num_samples: 5
  joint: False
