train:
  name: RBF/500
  type: GP
  batch_size: 256
  shuffle: True
  drop_last: True
  gp:
    kernel: !include configs/gp/rbf/kernel.yaml
    data_size: 51200
    max_num_points: 50
    x_range: [-2, 2]
    t_noise: null
valid:  !include configs/gp/rbf/datasets_test.yaml
test:   !include configs/gp/rbf/datasets_test.yaml
shapes: !include configs/gp/gp_shapes.yaml
