datasets:  !include configs/gp/rbf/500/datasets.yaml
model:     !include configs/gp/models/neubanp.yaml
optimizer: !include configs/gp/optimizer.yaml
train:     !include configs/gp/rbf/500/train.yaml
test:      !include configs/gp/rbf/test.yaml
