datasets:  !include configs/gp/periodic/050/datasets.yaml
model:     !include configs/gp/models/convcnp.yaml
optimizer: !include configs/gp/optimizer.yaml
train:     !include configs/gp/periodic/050/train.yaml
test:      !include configs/gp/periodic/test.yaml
