datasets:  !include configs/gp/periodic/125/datasets.yaml
model:     !include configs/gp/models/banp.yaml
optimizer: !include configs/gp/optimizer.yaml
train:     !include configs/gp/periodic/125/train.yaml
test:      !include configs/gp/periodic/test.yaml
