datasets:  !include configs/image/svhn/datasets.yaml
model:     !include configs/image/models/cnp.yaml
optimizer: !include configs/image/optimizer.yaml
train:     !include configs/image/svhn/train.yaml
test:      !include configs/image/svhn/test.yaml
