train:
  name: SVHN
  type: Image
  batch_size: 32
  shuffle: True
  drop_last: True
  image:
    name: SVHN
    root: ./datasets
    split: train
    full_tar: False
    max_num_points: 200
    flatten: False
valid:
  name: SVHN
  type: Image
  batch_size: 64
  shuffle: False
  drop_last: True
  image:
    name: SVHN
    root: ./datasets
    split: valid
    full_tar: True
    max_num_points: 200
    flatten: False
test:
  name: SVHN
  type: Image
  batch_size: 64
  shuffle: False
  drop_last: True
  image:
    name: SVHN
    root: ./datasets
    split: test
    full_tar: True
    max_num_points: 200
    flatten: False
shapes:
  x: [32, 32, 2]
  y: [32, 32, 3]
  mask_ctx: [32, 32]
  mask_tar: [32, 32]
