name: CANP
kwargs:
  r_dim: 128
  sa_heads: 8
  ca_heads: 8
  transform_qk_dims: [128, 128, 128, 128, 128]
  encoder_dims: [128, 128, 128, 128, 128]
  decoder_dims: [128, 128, 128]
train_kwargs: {}
valid_kwargs: {}
test_kwargs: {}
