name: Periodic
type: GP
batch_size: 512
shuffle: False
drop_last: True
gp:
  kernel: !include configs/gp/periodic/kernel.yaml
  data_size: 5120
  max_num_points: 50
  x_range: [-2, 2]
  t_noise: null
