datasets:  !include configs/gp/t_noise/100/datasets.yaml
model:     !include configs/gp/models/convcnp.yaml
optimizer: !include configs/gp/optimizer.yaml
train:     !include configs/gp/t_noise/100/train.yaml
test:      !include configs/gp/t_noise/test.yaml
