datasets:  !include configs/gp/rbf/250/datasets.yaml
model:     !include configs/gp/models/convcnp.yaml
optimizer: !include configs/gp/optimizer.yaml
train:     !include configs/gp/rbf/250/train.yaml
test:      !include configs/gp/rbf/test.yaml
