train:
  name: LotkaVolterra
  type: Sim2Real
  sim2real:
    name: LotkaVolterra
    split: train
    root: ./datasets
  batch_size: 64
  shuffle: True
  drop_last: True
valid:
  name: LotkaVolterra
  type: Sim2Real
  sim2real:
    name: LotkaVolterra
    split: valid
    root: ./datasets
  batch_size: 128
  shuffle: False
  drop_last: True
test:
  name: LotkaVolterra
  type: Sim2Real
  sim2real:
    name: LotkaVolterra
    split: test
    root: ./datasets
  batch_size: 128
  shuffle: False
  drop_last: False
shapes:
  x_ctx: [-1, 3, 1]
  y_ctx: [-1, 3, 2]
  mask_ctx: [-1, 3]
  x_tar: [-1, 3, 1]
  y_tar: [-1, 3, 2]
  mask_tar: [-1, 3]
