datasets:  !include configs/gp/t_noise/500/datasets.yaml
model:     !include configs/gp/models/neubnp.yaml
optimizer: !include configs/gp/optimizer.yaml
train:     !include configs/gp/t_noise/500/train.yaml
test:      !include configs/gp/t_noise/test.yaml
