train:
  name: Periodic/250
  type: GP
  batch_size: 256
  shuffle: True
  drop_last: True
  gp:
    kernel: !include configs/gp/periodic/kernel.yaml
    data_size: 102400
    max_num_points: 50
    x_range: [-2, 2]
    t_noise: null
valid:  !include configs/gp/periodic/datasets_test.yaml
test:   !include configs/gp/periodic/datasets_test.yaml
shapes: !include configs/gp/gp_shapes.yaml
