datasets:  !include configs/gp/periodic/250/datasets.yaml
model:     !include configs/gp/models/neubnp.yaml
optimizer: !include configs/gp/optimizer.yaml
train:     !include configs/gp/periodic/250/train.yaml
test:      !include configs/gp/periodic/test.yaml
