datasets:  !include configs/gp/rbf/125/datasets.yaml
model:     !include configs/gp/models/convnp.yaml
optimizer: !include configs/gp/optimizer.yaml
train:     !include configs/gp/rbf/125/train.yaml
test:      !include configs/gp/rbf/test.yaml
