datasets:  !include configs/gp/matern/125/datasets.yaml
model:     !include configs/gp/models/neubnp.yaml
optimizer: !include configs/gp/optimizer.yaml
train:     !include configs/gp/matern/125/train.yaml
test:      !include configs/gp/matern/test.yaml
