datasets:  !include configs/gp/t_noise/inf/datasets.yaml
model:     !include configs/gp/models/neubanp.yaml
optimizer: !include configs/gp/optimizer.yaml
train:     !include configs/gp/t_noise/inf/train.yaml
test:      !include configs/gp/t_noise/test.yaml
