datasets:  !include configs/gp/matern/250/datasets.yaml
model:     !include configs/gp/models/np.yaml
optimizer: !include configs/gp/optimizer.yaml
train:     !include configs/gp/matern/250/train.yaml
test:      !include configs/gp/matern/test.yaml
