datasets:  !include configs/gp/matern/500/datasets.yaml
model:     !include configs/gp/models/convnp.yaml
optimizer: !include configs/gp/optimizer.yaml
train:     !include configs/gp/matern/500/train.yaml
test:      !include configs/gp/matern/test.yaml
